version: '3'
services:
  front:
    build:
      context: ./front-dockerfile
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./VueNginxSample_front/app:/app
    tty: true
    #restart: on-failure
    # command: yarn dev
    # command: yarn nuxt start
    working_dir: /app
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/conf.d:/etc/nginx/conf.d
      - ./server/log:/var/log/nginx
    tty: true
    #restart: on-failure

  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - 18080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home

volumes:
  front_node_modules: