version: '3'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./front/app:/app
    tty: true
    #restart: on-failure
    # command: yarn dev
    # command: yarn nuxt start 本番
    working_dir: /app

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/conf.d:/etc/nginx/conf.d
      - ./server/log:/var/log/nginx
    tty: true
    #restart: on-failure

volumes:
  front_node_modules: